/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface Paths {
  "/pets": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all pets */
    get: Operations["listPets"]
    put?: never
    /** Create a pet */
    post: Operations["createPet"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/pets/{petId}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get a pet by ID */
    get: Operations["getPet"]
    put?: never
    post?: never
    /** Delete a pet */
    delete: Operations["deletePet"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type Webhooks = Record<string, never>
export interface Components {
  schemas: {
    Pet: {
      id: string
      name: string
      tag?: string
    }
    NewPet: {
      name: string
      tag?: string
    }
    Error: {
      code: number
      message: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type Defs = Record<string, never>
export interface Operations {
  listPets: {
    parameters: {
      query?: {
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: string
        }
        content: {
          "application/json": Array<Components["schemas"]["Pet"]>
        }
      }
      /** @description Internal error */
      500: {
        headers: {
          [name: string]: string
        }
        content: {
          "application/json": Components["schemas"]["Error"]
        }
      }
    }
  }
  createPet: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": Components["schemas"]["NewPet"]
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: string
        }
        content: {
          "application/json": Components["schemas"]["Pet"]
        }
      }
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: string
        }
        content: {
          "application/json": Components["schemas"]["Error"]
        }
      }
      /** @description Internal error */
      500: {
        headers: {
          [name: string]: string
        }
        content: {
          "application/json": Components["schemas"]["Error"]
        }
      }
    }
  }
  getPet: {
    parameters: {
      query?: never
      header?: never
      path: {
        petId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: string
        }
        content: {
          "application/json": Components["schemas"]["Pet"]
        }
      }
      /** @description Not found */
      404: {
        headers: {
          [name: string]: string
        }
        content: {
          "application/json": Components["schemas"]["Error"]
        }
      }
      /** @description Internal error */
      500: {
        headers: {
          [name: string]: string
        }
        content: {
          "application/json": Components["schemas"]["Error"]
        }
      }
    }
  }
  deletePet: {
    parameters: {
      query?: never
      header?: never
      path: {
        petId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Deleted successfully */
      204: {
        headers: {
          [name: string]: string
        }
        content?: never
      }
      /** @description Not found */
      404: {
        headers: {
          [name: string]: string
        }
        content: {
          "application/json": Components["schemas"]["Error"]
        }
      }
      /** @description Internal error */
      500: {
        headers: {
          [name: string]: string
        }
        content: {
          "application/json": Components["schemas"]["Error"]
        }
      }
    }
  }
}
